ERROR="Error"
MESSAGE="Message"
RECORD_CREATE_SUCCESSFULLY="Record created successfully."
RECORD_DELETE_SUCCESSFULLY="Record delete successfully."
RECORD_UPDATE_SUCCESSFULLY="Record update successfully."
SOMETHING_WENT_WRONG="Something went wrong."